export const presets = {
    topLeft: {
        "--align": "start",
        "--top": "0%",
        "--left": "0%",
        "--translateX": "0%",
        "--translateY": "0%",
    },
    topMiddle: {
        "--align": "center",
        "--top": "0%",
        "--left": "50%",
        "--translateX": "-50%",
        "--translateY": "0%",
    },
    topRight: {
        "--align": "end",
        "--top": "0%",
        "--right": "0%",
        "--translateX": "0%",
        "--translateY": "0%",
    },
    middleLeft: {
        "--align": "start",
        "--top": "50%",
        "--left": "0%",
        "--translateX": "0%",
        "--translateY": "-50%",
    },
    middle: {
        "--align": "center",
        "--top": "50%",
        "--left": "50%",
        "--translateX": "-50%",
        "--translateY": "-50%",
    },
    middleRight: {
        "--align": "end",
        "--top": "50%",
        "--right": "0%",
        "--translateX": "0%",
        "--translateY": "-50%",
    },
    bottomLeft: {
        "--align": "start",
        "--bottom": "0%",
        "--left": "0%",
        "--translateX": "0%",
        "--translateY": "0%",
    },
    bottomMiddle: {
        "--align": "center",
        "--bottom": "0%",
        "--left": "50%",
        "--translateX": "-50%",
        "--translateY": "0%",
    },
    bottomRight: {
        "--align": "end",
        "--bottom": "0%",
        "--right": "0%",
        "--translateX": "0%",
        "--translateY": "0%",
    },
};
